#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)

profile=${1:-}
if [[ -z "$profile" ]]; then
  echo "Usage: scripts/use-env-profile.sh <anvil|sepolia>"
  exit 1
fi

shared_file="${ROOT_DIR}/.env.shared"
profile_file="${ROOT_DIR}/.env.${profile}"
target_file="${ROOT_DIR}/.env"

if [[ ! -f "$shared_file" ]]; then
  echo "Missing ${shared_file}"
  echo "Create it from .env.shared.example first."
  exit 1
fi

if [[ ! -f "$profile_file" ]]; then
  echo "Missing ${profile_file}"
  echo "Create it from .env.${profile}.example first."
  exit 1
fi

tmp_file=$(mktemp)
{
  echo "# Generated from .env.shared + .env.${profile}"
  echo "# Do not edit this file directly unless you intentionally want a one-off override."
  echo
  cat "$shared_file"
  echo
  cat "$profile_file"
} > "$tmp_file"

mv "$tmp_file" "$target_file"
echo "Wrote ${target_file} from ${shared_file} + ${profile_file}"
